### ISSUE TITLE
Level up screen sometimes has leftover cruft

### ISSUE THREAD

**Issue by chris-torrence** [6502-workshop/NA#1]
When I leveled up, the screen looks like it still had some of the "press ESC" from the previous text screen. It didn't happen the next time I leveled up. Here's a screenshot:
<img width="1120" alt="screen shot 2018-10-30 at 8 44 47 pm" src="https://user-images.githubusercontent.com/5461379/47921267-c5752d00-de79-11e8-81eb-f264b9290a53.png">

**Comment by 6502-workshop** [comment]
Thanks! This was an issue in release R0.58. It was fixed in R0.59. If you'd like to upgrade you can transfer your saved game data by moving the file DATA.SAVED.GAME from the R0.58 image to the R0.59 image using Ciderpress. If you'd like me to resend the R0.59 image just let me know.

**Comment by chris-torrence** [comment]
Hmmm, I could have sworn that I was using R0.59. I'll have to check when I get home.

**Comment by chris-torrence** [comment]
Just confirmed that I'm running R0.59.

**Comment by 6502-workshop** [comment]
Ok, thanks for checking, and sorry for jumping to conclusions. For various reasons, I'm just shocked this bug still exists. Could you attach the disk image to this github issue? I may need to go spelunking.

**Comment by 6502-workshop** [comment]
Wait, nevermind. I don't need the image. I just confirmed the fix for this issue was applied after R0.59 in github commit cbc375ec5e23e6f64f189a6343aad659c80d989d
