### ISSUE TITLE
Missing word in horse livery dialogue, also shorten text

### ISSUE THREAD

**Issue by chris-torrence** [6502-workshop/NA#10]
Should be "**in** the region"
<img width="700" alt="screen shot 2018-11-03 at 3 39 39 pm" src="https://user-images.githubusercontent.com/5461379/47957612-d196e280-df7e-11e8-8d9e-93d894d56ee2.png">
Also, I wonder if the text could be shortened slightly, to avoid the extra key press? Something like: "I have the most reliable horses in the region, only 500. Buy one? (y/n)"

**Comment by 6502-workshop** [comment]
Thanks. Done. Typo and any key prompt addressed. Here is what it looks like:

![screen shot 2018-11-03 at 6 04 56 pm](https://user-images.githubusercontent.com/19576990/47958134-0d3ba780-df93-11e8-936e-3f281605ae60.png)
