### ISSUE TITLE
Camp while on horse shows scene on the boat

### ISSUE THREAD

**Issue by chris-torrence** [6502-workshop/NA#15]
If I camp while riding a horse, it shows the "boat" scene instead. Seems like the normal camp scene would be fine, unless you want to get fancy and have one with a horse...
<img width="1094" alt="screen shot 2018-11-04 at 10 24 43 am" src="https://user-images.githubusercontent.com/5461379/47967574-f42b0900-e01b-11e8-95ab-cd6f22af557d.png">

**Comment by 6502-workshop** [comment]
Good catch! The intention was to display the wilderness image rather than horse around with a special image. It's fixed for the next release.

**Comment by f1nutz** [comment]
I can probably add a horse to the wilderness image if you want that specifically.
We would then have the 2 options with or without horse.
your call though

**Comment by 6502-workshop** [comment]
Bill, thanks for the offer! It's not safe to do this art now, but I've flagged this option for review after we have a better idea of available player disk space available (once we have a full beta release).

**Comment by 6502-workshop** [comment]
Ah, that's a good point. I agree.
