### ISSUE TITLE
Text for "Less Punny Mace" should be "Less Puny Mace"?

### ISSUE THREAD

**Issue by chris-torrence** [6502-workshop/NA#3]
In the castle's weapons shop, should "Less Punny Mace" be "Less Puny Mace"?
<img width="671" alt="screen shot 2018-11-02 at 2 24 46 pm" src="https://user-images.githubusercontent.com/5461379/47938931-33861800-deab-11e8-8095-5e5bb966f946.png">

**Comment by 6502-workshop** [comment]
Chris, yes, good catch. Fixed.
