### ISSUE TITLE
'No object found' for chest in castle upstairs

### ISSUE THREAD

**Issue by chris-torrence** [6502-workshop/NA#4]
I'm in a room on the 2nd floor of the castle, over on the west side. If I try to "Open" either chest, it response with 'No object found'.
<img width="676" alt="screen shot 2018-11-02 at 6 18 56 pm" src="https://user-images.githubusercontent.com/5461379/47946003-f2523000-decb-11e8-8f1e-520ea23655f9.png">

**Comment by 6502-workshop** [comment]
fixed for next release.
