### ISSUE TITLE
Castle healer - paid gold for heal but then hit ESC

### ISSUE THREAD

**Issue by chris-torrence** [6502-workshop/NA#5]
Not sure if this is a bug. I paid the 5gp for heal, but then changed my mind when I realized it only healed 1 character. I hit ESC which cancelled the transaction (no healing) but the 5gp was already deducted. Not a big deal but I wasn't sure if maybe it should have waited until I picked a character before taking the gold?

**Comment by 6502-workshop** [comment]
Thanks. The behavior doesn't seem ideal. I'll see if I can fix it.

**Comment by 6502-workshop** [comment]
fixed for next release.
