### ISSUE TITLE
Should join be in caps rather than quotes?

### ISSUE THREAD

**Issue by f1nutz** [6502-workshop/NA#57]
Since we went with the caps for key words in dialogue maybe this text should be in caps?
I realize it is telling you to use the word with another character so does make sense in this  context
Would also be funny to have this character respond negatively to the JOIN dialogue option.
![image](https://user-images.githubusercontent.com/44733387/49344907-4ecf7900-f64b-11e8-9b16-ee674feffbdb.png)

**Comment by 6502-workshop** [comment]
Ah, yes. That is a wrinkle. I think the best solution is what you suggest, capitalize it and have this guy respond to it too, declining the invitation. 

I've implemented that for the next release.
